theme: minima
title: Learning how to use GitHub
author: thomasthaddeus
email: thomasthaddeus@cityuniversity.edu
description: > # this means to ignore newlines until "baseurl:"
  Nothing to write about just a boring description.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  thomasthaddeus
show_excerpts: true # set to false to remove excerpts on the homepage
