# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: Thads Tech Blog

theme: jekyll-theme-cayman
title: Learning how to use GitHub
author: Thaddeus Thomas
email: thomasthaddeus@cityuniversity.edu
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my blog. I talk about all things interesting to me.
  For now lets call it tech talk.
url: http://apparellnstuff.me/blog
# social links
twitter_username: thaddeusmaxima # DO NOT include the @ character, or else the build will fail!
github_username:  thomasthaddeus
show_excerpts: true # set to false to remove excerpts on the homepage

# Build settings
markdown: kramdown
plugins:
  - jekyll-avatar
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-github-metadata
  - jekyll-mentions
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-sass-converter
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings

# Exclude from processing.
# The following items will not be processed, by default.
exclude:
  - Gemfile
  - Gemfile.lock

collections:
  ctfs_and_challenges:
    output: true
    permalink: /:collection/:path


# The directory for category index pages. Change it to something else if
# for example you want links like /categories/category1 instead of /category1
category_dir: /

# Uncomment if you are planning to run the blog in a subdirectory
# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# Example, you must use http://localhost:4000/path/to/blog
#baseurl: /path/to/blog
# baseurl:


paginate: 3
gems: [jekyll-paginate]
