theme: minima
title: Learning how to use GitHub
author: thomasthaddeus
email: thomasthaddeus@cityuniversity.edu
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my blog. I talk about all things interesting to me.
  For now lets call it tech talk.
# social links
twitter_username: thaddeusmaxima # DO NOT include the @ character, or else the build will fail!
github_username:  thomasthaddeus
show_excerpts: true # set to false to remove excerpts on the homepage
